# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc_win.ui'
#
# Created: Sun Nov  8 10:42:23 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(376, 458)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lineEdit = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 20, 341, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.pb_1 = QtGui.QPushButton(self.centralwidget)
        self.pb_1.setGeometry(QtCore.QRect(31, 141, 61, 51))
        self.pb_1.setObjectName(_fromUtf8("pb_1"))
        self.pb_2 = QtGui.QPushButton(self.centralwidget)
        self.pb_2.setGeometry(QtCore.QRect(112, 141, 61, 51))
        self.pb_2.setObjectName(_fromUtf8("pb_2"))
        self.pb_9 = QtGui.QPushButton(self.centralwidget)
        self.pb_9.setGeometry(QtCore.QRect(193, 260, 61, 51))
        self.pb_9.setObjectName(_fromUtf8("pb_9"))
        self.pb_6 = QtGui.QPushButton(self.centralwidget)
        self.pb_6.setGeometry(QtCore.QRect(193, 199, 61, 51))
        self.pb_6.setObjectName(_fromUtf8("pb_6"))
        self.pb_8 = QtGui.QPushButton(self.centralwidget)
        self.pb_8.setGeometry(QtCore.QRect(112, 260, 61, 51))
        self.pb_8.setObjectName(_fromUtf8("pb_8"))
        self.pb_4 = QtGui.QPushButton(self.centralwidget)
        self.pb_4.setGeometry(QtCore.QRect(31, 200, 61, 51))
        self.pb_4.setObjectName(_fromUtf8("pb_4"))
        self.pb_3 = QtGui.QPushButton(self.centralwidget)
        self.pb_3.setGeometry(QtCore.QRect(193, 141, 61, 51))
        self.pb_3.setObjectName(_fromUtf8("pb_3"))
        self.pb_5 = QtGui.QPushButton(self.centralwidget)
        self.pb_5.setGeometry(QtCore.QRect(112, 199, 61, 51))
        self.pb_5.setObjectName(_fromUtf8("pb_5"))
        self.pb_7 = QtGui.QPushButton(self.centralwidget)
        self.pb_7.setGeometry(QtCore.QRect(31, 260, 61, 51))
        self.pb_7.setObjectName(_fromUtf8("pb_7"))
        self.pushButton_10 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_10.setGeometry(QtCore.QRect(280, 240, 75, 101))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pb_add = QtGui.QPushButton(self.centralwidget)
        self.pb_add.setGeometry(QtCore.QRect(270, 140, 41, 41))
        self.pb_add.setObjectName(_fromUtf8("pb_add"))
        self.pb_sub = QtGui.QPushButton(self.centralwidget)
        self.pb_sub.setGeometry(QtCore.QRect(320, 140, 41, 41))
        self.pb_sub.setObjectName(_fromUtf8("pb_sub"))
        self.pb_mul = QtGui.QPushButton(self.centralwidget)
        self.pb_mul.setGeometry(QtCore.QRect(270, 190, 41, 41))
        self.pb_mul.setObjectName(_fromUtf8("pb_mul"))
        self.pb_div = QtGui.QPushButton(self.centralwidget)
        self.pb_div.setGeometry(QtCore.QRect(320, 190, 41, 41))
        self.pb_div.setObjectName(_fromUtf8("pb_div"))
        self.pb = QtGui.QPushButton(self.centralwidget)
        self.pb.setGeometry(QtCore.QRect(30, 320, 61, 51))
        self.pb.setObjectName(_fromUtf8("pb"))
        self.pb_0 = QtGui.QPushButton(self.centralwidget)
        self.pb_0.setGeometry(QtCore.QRect(110, 320, 61, 51))
        self.pb_0.setObjectName(_fromUtf8("pb_0"))
        self.pb_C = QtGui.QPushButton(self.centralwidget)
        self.pb_C.setGeometry(QtCore.QRect(30, 80, 61, 51))
        self.pb_C.setObjectName(_fromUtf8("pb_C"))
        self.pb_CE = QtGui.QPushButton(self.centralwidget)
        self.pb_CE.setGeometry(QtCore.QRect(110, 80, 61, 51))
        self.pb_CE.setObjectName(_fromUtf8("pb_CE"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 376, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(MainWindow)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionAdd = QtGui.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAdd.setIcon(icon)
        self.actionAdd.setObjectName(_fromUtf8("actionAdd"))
        self.actionSub = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/subtract.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionSub.setIcon(icon1)
        self.actionSub.setObjectName(_fromUtf8("actionSub"))
        self.actionMul = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/multiply-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionMul.setIcon(icon2)
        self.actionMul.setObjectName(_fromUtf8("actionMul"))
        self.actionDiv = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/Icons/mathematic-divide-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionDiv.setIcon(icon3)
        self.actionDiv.setObjectName(_fromUtf8("actionDiv"))
        self.menuFile.addAction(self.actionAdd)
        self.menuFile.addAction(self.actionSub)
        self.menuFile.addAction(self.actionMul)
        self.menuFile.addAction(self.actionDiv)
        self.menubar.addAction(self.menuFile.menuAction())
        self.toolBar.addAction(self.actionAdd)
        self.toolBar.addAction(self.actionSub)
        self.toolBar.addAction(self.actionMul)
        self.toolBar.addAction(self.actionDiv)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.pb_1.setText(_translate("MainWindow", "1", None))
        self.pb_2.setText(_translate("MainWindow", "2", None))
        self.pb_9.setText(_translate("MainWindow", "9", None))
        self.pb_6.setText(_translate("MainWindow", "6", None))
        self.pb_8.setText(_translate("MainWindow", "8", None))
        self.pb_4.setText(_translate("MainWindow", "4", None))
        self.pb_3.setText(_translate("MainWindow", "3", None))
        self.pb_5.setText(_translate("MainWindow", "5", None))
        self.pb_7.setText(_translate("MainWindow", "7", None))
        self.pushButton_10.setText(_translate("MainWindow", "=", None))
        self.pb_add.setText(_translate("MainWindow", "+", None))
        self.pb_sub.setText(_translate("MainWindow", "-", None))
        self.pb_mul.setText(_translate("MainWindow", "X", None))
        self.pb_div.setText(_translate("MainWindow", "/", None))
        self.pb.setText(_translate("MainWindow", "+/-", None))
        self.pb_0.setText(_translate("MainWindow", "0", None))
        self.pb_C.setText(_translate("MainWindow", "C", None))
        self.pb_CE.setText(_translate("MainWindow", "CE", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionAdd.setText(_translate("MainWindow", "Add", None))
        self.actionAdd.setShortcut(_translate("MainWindow", "Ctrl+A", None))
        self.actionSub.setText(_translate("MainWindow", "Subtract", None))
        self.actionSub.setShortcut(_translate("MainWindow", "Ctrl+S", None))
        self.actionMul.setText(_translate("MainWindow", "Multiply", None))
        self.actionMul.setShortcut(_translate("MainWindow", "Ctrl+M", None))
        self.actionDiv.setText(_translate("MainWindow", "Divide", None))
        self.actionDiv.setShortcut(_translate("MainWindow", "Ctrl+D", None))

import Calc_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

