# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TelDir.ui'
#
# Created: Sat Jan 23 11:28:06 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(613, 480)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(22, 101, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(22, 153, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(22, 205, 81, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(22, 361, 121, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(22, 257, 201, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(22, 309, 71, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.lne_id = QtGui.QLineEdit(self.centralwidget)
        self.lne_id.setGeometry(QtCore.QRect(130, 101, 133, 20))
        self.lne_id.setObjectName(_fromUtf8("lne_id"))
        self.lne_la = QtGui.QLineEdit(self.centralwidget)
        self.lne_la.setGeometry(QtCore.QRect(130, 309, 133, 20))
        self.lne_la.setObjectName(_fromUtf8("lne_la"))
        self.lne_ph = QtGui.QLineEdit(self.centralwidget)
        self.lne_ph.setGeometry(QtCore.QRect(130, 257, 133, 20))
        self.lne_ph.setObjectName(_fromUtf8("lne_ph"))
        self.lne_na = QtGui.QLineEdit(self.centralwidget)
        self.lne_na.setGeometry(QtCore.QRect(130, 150, 133, 20))
        self.lne_na.setObjectName(_fromUtf8("lne_na"))
        self.lne_ni = QtGui.QLineEdit(self.centralwidget)
        self.lne_ni.setGeometry(QtCore.QRect(130, 205, 133, 20))
        self.lne_ni.setObjectName(_fromUtf8("lne_ni"))
        self.lne_sh = QtGui.QLineEdit(self.centralwidget)
        self.lne_sh.setGeometry(QtCore.QRect(130, 361, 133, 20))
        self.lne_sh.setObjectName(_fromUtf8("lne_sh"))
        self.pb_add = QtGui.QPushButton(self.centralwidget)
        self.pb_add.setGeometry(QtCore.QRect(21, 410, 71, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(8)
        self.pb_add.setFont(font)
        self.pb_add.setObjectName(_fromUtf8("pb_add"))
        self.pb_save = QtGui.QPushButton(self.centralwidget)
        self.pb_save.setGeometry(QtCore.QRect(116, 410, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(8)
        self.pb_save.setFont(font)
        self.pb_save.setObjectName(_fromUtf8("pb_save"))
        self.pb_upd = QtGui.QPushButton(self.centralwidget)
        self.pb_upd.setGeometry(QtCore.QRect(211, 410, 78, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(8)
        self.pb_upd.setFont(font)
        self.pb_upd.setObjectName(_fromUtf8("pb_upd"))
        self.pb_select = QtGui.QPushButton(self.centralwidget)
        self.pb_select.setGeometry(QtCore.QRect(309, 410, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(8)
        self.pb_select.setFont(font)
        self.pb_select.setObjectName(_fromUtf8("pb_select"))
        self.pb_refresh = QtGui.QPushButton(self.centralwidget)
        self.pb_refresh.setGeometry(QtCore.QRect(404, 410, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(8)
        self.pb_refresh.setFont(font)
        self.pb_refresh.setObjectName(_fromUtf8("pb_refresh"))
        self.pushButton_6 = QtGui.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(499, 410, 75, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(8)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.lwe = QtGui.QListWidget(self.centralwidget)
        self.lwe.setGeometry(QtCore.QRect(280, 99, 321, 271))
        self.lwe.setObjectName(_fromUtf8("lwe"))
        item = QtGui.QListWidgetItem()
        self.lwe.addItem(item)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(21, 60, 69, 18))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Berlin Sans FB"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 561, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("MS Serif"))
        font.setPointSize(22)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEdit_7 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(121, 61, 121, 20))
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.lineEdit_8 = QtGui.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(272, 61, 121, 20))
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 613, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Id:", None))
        self.label_2.setText(_translate("MainWindow", "Name:", None))
        self.label_3.setText(_translate("MainWindow", "Nickname:", None))
        self.label_4.setText(_translate("MainWindow", "Short Adress:", None))
        self.label_5.setText(_translate("MainWindow", "Telephone no.:", None))
        self.label_6.setText(_translate("MainWindow", "Landline:", None))
        self.pb_add.setText(_translate("MainWindow", "Add", None))
        self.pb_save.setText(_translate("MainWindow", "Save", None))
        self.pb_upd.setText(_translate("MainWindow", "Update Details", None))
        self.pb_select.setText(_translate("MainWindow", "Select", None))
        self.pb_refresh.setText(_translate("MainWindow", "Refresh", None))
        self.pushButton_6.setText(_translate("MainWindow", "Search", None))
        __sortingEnabled = self.lwe.isSortingEnabled()
        self.lwe.setSortingEnabled(False)
        item = self.lwe.item(0)
        item.setText(_translate("MainWindow", "Id             Name           Nickname       Phone No.      Landline       Short Address", None))
        self.lwe.setSortingEnabled(__sortingEnabled)
        self.label_7.setText(_translate("MainWindow", "Search By:", None))
        self.label_8.setText(_translate("MainWindow", "Telephone Directory", None))
        self.lineEdit_7.setText(_translate("MainWindow", "[Enter Name]", None))
        self.lineEdit_8.setText(_translate("MainWindow", "[Enter Proffesion]", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

